import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <header className="main-header">
          <div className="main-title">
            <picture className="main-logo">
              <img
                src="filbo-logo.svg"
                alt="Feria Internacional del Libro de Bogotá"
              ></img>
            </picture>
            <h1>
              <span className="main-title__filbo">FILBo</span>
              <span>Independiente</span>
            </h1>
          </div>
          <div className="main-date">17 abril al 02 mayo en Corferias</div>
        </header>
        <main>{children}</main>
        <footer className="main-footer">
          <p className="main-footer__logo">
            <span className="main-footer__filbo">FILBo</span>
            <span>Independiente</span>
          </p>
        </footer>
      </body>
    </html>
  );
}
